FROM ubuntu:16.04

MAINTAINER Alper Celik
# this dockerfile is the base for clinseqr all the actual apps will be built on top of this

RUN apt-get update --yes && \
    apt-get upgrade --yes && \
    apt-get install curl --yes && \
    apt-get install libxml2 --yes && \
    apt-get install git --yes && \
    apt-get install libcurl4-openssl-dev --yes && \
    apt-get install libssl-dev --yes && \
    apt-get install libxml2-dev --yes && \
    apt-get install wget --yes && \
    apt-get install sed --yes && \
    apt-get install pandoc --yes && \
    apt-get install pandoc-citeproc --yes && \
    apt-get install libcairo2-dev --yes && \
    apt-get install libxt-dev --yes && \
    apt-get install libssl-dev --yes && \
    apt-get install libssh2-1-dev --yes && \
    apt-get install sqlite3 --yes && \
    apt-get install libssl1.0.0 --yes && \
    apt-get install libmpfr-dev --yes && \
    apt-get install libgit2-dev --yes && \
    apt-get install libudunits2-dev --yes && \
    apt-get install libxml2-dev --yes && \
    apt-get install libv8-3.14-dev --yes && \
    apt-get install libpoppler-glib-dev --yes && \
    apt-get install libgeos-dev --yes && \
    apt-get install libgdal1i --yes

RUN apt-get install -y software-properties-common --yes && \
    add-apt-repository ppa:marutter/rrutter3.5 --yes && \
    apt-get update && \
    apt-get install  r-base r-base-dev --yes

COPY package_install.R /package_install.R

RUN Rscript package_install.R

