FROM celalp/clinseqr_base

MAINTAINER Alper Celik Ph.D

# get the repo, from github

RUN ls -l

RUN git clone https://github.com/celalp/clin_seqR
RUN wget https://raw.githubusercontent.com/openanalytics/shinyproxy-template/master/Rprofile.site

RUN mv Rprofile.site /usr/lib/R/etc/Rprofile.site

RUN ls -l clin_seqR/

# mount the folder that has the data

EXPOSE 3838

# run the shiny app

CMD ["R", "-e", "shiny::runApp('/clin_seqR/clin_seqR_gtex')"]
